server:
  port: 8088

---


keycloak-client:
  server-url: http://localhost:9090
  realm: master

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: dashboard
          uri: http://localhost:8081
          predicates:
            - Path= /dashboards/**
        - id: drive
          uri: http://localhost:8082
          predicates:
            - Path=/files/** 
        - id: indexer
          uri: http://localhost:8083
          predicates:
            - Path=/indices/** 
        - id: video processing
          uri: http://localhost:8084
          predicates:
            - Path=/videos/** 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/notificationHistories/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "gateway-path/login/oauth2/code/client-name"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

---

spring:
  profiles: docker
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /dashboards/**
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/files/** 
        - id: indexer
          uri: http://indexer:8080
          predicates:
            - Path=/indices/** 
        - id: video processing
          uri: http://video processing:8080
          predicates:
            - Path=/videos/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notificationHistories/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080